language: java
sudo: true
jdk:
  - oraclejdk8
before_cache: 
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock #travis recommended solution for avoiding cache problems with gradle
cache:
  directories:
    - $HOME/.gradle/caches/ 
    - $HOME/.gradle/wrapper/
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends r-base-dev r-recommended qpdf
env:
 global:
  #gradle needs this
  - TERM=dumb
  #limit gradle jvm memory
  - GRADLE_OPTS=-Xmx1024m
script:
  - gradle test
