sudo: false
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
script:
- sbt clean coverage test && sbt coverageAggregate
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_install:
- pip install --user codecov
after_success:
- codecov
- test "$TRAVIS_REPO_SLUG" == 'fulcrumgenomics/fgbio' && test "$TRAVIS_PULL_REQUEST" == 'false' && test "$TRAVIS_BRANCH" == 'master' && sbt 'set version := version.value + "." + System.getenv("TRAVIS_BUILD_NUMBER")' publish
env:
  global:
  - secure: vaRMSZjO483veCz1AhgbN0U2E1QGGjcFFkLEq1EdsTUdCInKMVtT85Csq/U1Blj3noW8es2tnPrGHewQ/aqxSMZzlJO0xiZCAsF0vD55vSicQgs5LML1Te5FJzf1WXcripxgv15OxmPWIlBvfZmFXSiOJMZ+7PHWAGz2ua4FOXFqpsM2LCWquIv2DL4qTNrpmqn/RB65mjcvqYmmHOEzzCGWcUkCva324z+SKixUrx5kDrH85Vk/4VZTgXKSiC0XuGzgUP01NSgF4Gxz5hRWSmjOky+vpoZzka+JbuZy5FVTb01XyQoD70sAB+rtMXOJGaqrCxDM+6r3t+vf1BDmvjgZt/R9lR4syp4+K+D6vtTqCUHUxASaaAKcBnflGCfwArYvGny6XTQlvvjab572rIyY7Ib5ItO+9Xe+g8a0sro/0AD1oqsHE8V0veokxOlA26bACrkzVwm+WCLVyj6Ik09a9zXtar5tZkW5YDt/sJjHjBSqkbupTW/QmjUqyZUO7xKvED0BcJELiAGqz8WWLYlV5vu8DWVEBLMZY47vKIIzfiRxx1a0EVrUPU4qX7MWuqpgPtIyaQkcAsuroT5HeA/ilnuVA7rSLIpvxB9xedQQwrPMxkD2f1EjUgfOge8oyLg4bbp9m4WedFu4lsrHQ0xNJ+IAMvIjgIcv/DZP6KI=
  - secure: 2J6iAFuJGWtTGP/UbWQieBdy55c8dW5FuIF/rl82y5SGE1mh566nPsLzD74d6867Gtj9iwFNAt+yQM9fVqeG77ovXZ50EtNFAmRGHBNra9a1QKiD1Y+S1eeKvZ+avsSK7LIxcmHsAW9txqlDOcBrPvLhC1EUjz5q9LviPfbx9muhvZIwShWwzHi/48xeH8GvXU5zi8Tly6rW/1p0EA7atgAq3u34Z3cC1SrwvZW3+vNAV1/UM5c/J2eTvAPlXuDD0W3/H+swac/G21iaNX0utkQf9NY7IZH5aiUNRsHN8653D6oXj4AB39mdSUD9t6SFgjg9fy4UI88MokMzycaV+TP6TuM/mryEyK6KJt/caNGSbTfoxxbEI9jdjZxIrQE2KYdsTHpEygN7TUHimvifM1IJG8L92ivrI8bqWnPwrcvzgX499vAKdOlUY0KL0uNZyvygerFCTfqj2PRu4CeoO54lmRo+3xmeMXrEzvB4pXZOd8vzVmiAFMkEWUNIh11ClBzzHpdKEPalglwTDvPp+jktcasZpNIYlG3vlts2kgzT7+X0d7qiUZRchYc1SJ3CeQdtfAz+CrjwADVNoNZgUPqD90YbwA5+hzbT14k24yxnDFu0HyyPF5oXzpLx/2x4axsPrTRgbi+xMi/lbfBX8Ucg5AU3qpymSNeGbbzUVXQ=
